version: '3.3'

services:
  myapp:
    image: medamine12/devopsproject
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:4.2.2
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    # No authentication-related environment variables or command here
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
