version: '3.3'

services:
  myapp:
    image: medamine12/devopsproject
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:4.2.2
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: [--auth]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
